### ISSUE TITLE
API do Facebook nao funcional

### ISSUE THREAD

**Issue by leafax** [capellaresumo/UspAvalia#3]
Nao da para fazer login usando o facebook

**Comment by capella** [comment]
Vou arrumar no próximo final de semana, obrigado por avisar.

**Comment by capella** [comment]
Arrumado.

**Comment by capella** [comment]
Mais uma coisa, se quiser posso colocar um agradecimento em https://github.com/capella/UspAvalia/blob/master/view/sobre.php

**Comment by leafax** [comment]
Rafael Loureiro Castro, o agradecimento fica a sua descrição
Esse site tem uma premissa muito boa e vou tentar populariza-lo no meu instituto
