### ISSUE TITLE
Não está sendo possível acessar o site

### ISSUE THREAD

**Issue by danlawand** [capellaresumo/UspAvalia#5]
Ao entrar em `uspavalia.com` aparece uma sessão de login que antes não aparecia, com o título `Sato e Capella 2015`.

Ao ver a _response_ no console, o resultado foi esse:

Request URL: https://uspavalia.com/assets/fonts/glyphicons-halflings-regular.woff2
Request Method: GET
Status Code: 404

**Comment by capella** [comment]
@danlawand, obrigado por reporter o problema. Isso se deve a uma má configuração do NGINX na frente do site.

O UspAvalia carece de melhorias. Você tem interesse em saber mais e ajudar o projeto?
